# This is the configuration used to check the rubocop source code.

#inherit_from: .rubocop_todo.yml
require:
  - rubocop-rspec
  - rubocop-rails
    
AllCops:
  NewCops: enable
  
Style/CombinableLoops:
  Enabled: false
  Exclude: 
    - test/**/*

Metrics/BlockLength:
  Enabled: false
  Exclude:
    - db/schema.rb

Metrics/MethodLength:
  Enabled: true

Layout/LineLength:
  Enabled: false
  Exclude: 
    - test/**/*
